version: "3.8"
services:
  spring-boot-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-service:latest
    container_name: spring-boot-service
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgresql
    networks:
      - postgres
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresql-container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - postgresql
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: