server:
  servlet:
    context-path: ${URI_PATH:/}
  tomcat:
    use-relative-redirects: true
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: local
  application:
    name: spring-boot-module
  flyway:
    baselineOnMigrate: true

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    enabled: true